// SPDX-License-Identifier: Apache-2.0
import type { SpanRow } from './api';

/** Headers a client sets by itself, or that only make sense for the original connection. */
const SKIPPED_HEADERS = new Set([
  'host',
  'content-length',
  'connection',
  'accept-encoding',
  'traceparent',
  'tracestate',
  'baggage',
  'x-causeline-replay',
  'x-causeline-replay-session',
]);

export interface CapturedRequest {
  method: string;
  /** Path and query, e.g. /api/orders?draft=true */
  target: string;
  /** Full URL when the browser recorded one */
  url?: string;
  headers: [string, string][];
  body?: string;
  status?: number;
}

/** The request a REQUEST span describes, or undefined when it isn't one. */
export function capturedRequest(span: SpanRow): CapturedRequest | undefined {
  const a = span.attributes;
  const method = a['http.request.method'];
  if (span.kind !== 'REQUEST' || !method) {
    return undefined;
  }
  const path = a['url.path'] ?? (a['url.full'] ? new URL(a['url.full']).pathname : undefined) ?? a['http.route'] ?? '/';
  const query = a['url.query'] ?? (a['url.full'] ? new URL(a['url.full']).search.slice(1) : '');
  const headers = Object.entries(a)
    .filter(([key]) => key.startsWith('http.request.header.'))
    .map(([key, value]) => [key.slice('http.request.header.'.length), value] as [string, string])
    .filter(([name]) => !SKIPPED_HEADERS.has(name));
  const body = a['http.request.body'];
  const status = Number(a['http.response.status_code']);
  return {
    method,
    target: query ? `${path}?${query}` : path,
    url: a['url.full'],
    headers,
    // "[2048 bytes, image/png]" describes a body that wasn't recorded as text.
    body: body && !/^\[\d+ bytes/.test(body) ? body : undefined,
    status: Number.isFinite(status) && status > 0 ? status : undefined,
  };
}

const shellQuote = (value: string) => `'${value.replace(/'/g, `'\\''`)}'`;

/** A cURL command that sends the request again, with the headers and body that were captured. */
export function toCurl(request: CapturedRequest, origin: string): string {
  const url = request.url ?? origin.replace(/\/$/, '') + request.target;
  const lines = [`curl -X ${request.method} ${shellQuote(url)}`];
  for (const [name, value] of request.headers) {
    lines.push(`  -H ${shellQuote(`${name}: ${value}`)}`);
  }
  if (request.body !== undefined) {
    lines.push(`  --data-raw ${shellQuote(request.body)}`);
  }
  return lines.join(' \\\n');
}

const javaString = (value: string) =>
  `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r')}"`;

/** Credentials are left out of generated tests: they would end up committed to the repository. */
const isCredential = (name: string) => /authorization|cookie|token|secret|api-key|session/i.test(name);

function testName(request: CapturedRequest): string {
  const words = request.target.split('?')[0]?.split('/').filter((w) => w && !/^\d+$/.test(w)) ?? [];
  const tail = words.map((w) => w.replace(/[^A-Za-z0-9]/g, '')).map((w) => w.charAt(0).toUpperCase() + w.slice(1));
  return `${request.method.toLowerCase()}${tail.join('')}Replays`;
}

/** A JUnit test for a Spring MVC application, using MockMvc, asserting the status the original got. */
export function toMockMvcTest(request: CapturedRequest): string {
  const call = [`        mockMvc.perform(request(HttpMethod.${request.method}, ${javaString(request.target)})`];
  const contentType = request.headers.find(([n]) => n === 'content-type')?.[1];
  for (const [name, value] of request.headers) {
    if (name !== 'content-type' && !isCredential(name)) {
      call.push(`                .header(${javaString(name)}, ${javaString(value)})`);
    }
  }
  if (request.body !== undefined) {
    call.push(`                .contentType(${javaString(contentType ?? 'application/json')})`);
    call.push(`                .content(${javaString(request.body)}))`);
  } else {
    call[call.length - 1] += ')';
  }
  call.push(`                .andExpect(status().is(${request.status ?? 200}));`);
  return `// Generated by Causeline from a captured request. Credentials are left out.
// Needs org.springframework.boot:spring-boot-starter-webmvc-test in test scope.
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.HttpMethod;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest
@AutoConfigureMockMvc
class ${capitalize(testName(request))}Test {

    @Autowired
    MockMvc mockMvc;

    @Test
    void ${testName(request)}() throws Exception {
${call.join('\n')}
    }
}
`;
}

/** A JUnit test for a WebFlux application, using WebTestClient. */
export function toWebTestClientTest(request: CapturedRequest): string {
  const call = [`        client.method(HttpMethod.${request.method}).uri(${javaString(request.target)})`];
  const contentType = request.headers.find(([n]) => n === 'content-type')?.[1];
  for (const [name, value] of request.headers) {
    if (name !== 'content-type' && !isCredential(name)) {
      call.push(`                .header(${javaString(name)}, ${javaString(value)})`);
    }
  }
  if (request.body !== undefined) {
    call.push(`                .contentType(MediaType.parseMediaType(${javaString(contentType ?? 'application/json')}))`);
    call.push(`                .bodyValue(${javaString(request.body)})`);
  }
  call.push('                .exchange()');
  call.push(`                .expectStatus().isEqualTo(${request.status ?? 200});`);
  return `// Generated by Causeline from a captured request. Credentials are left out.
// Needs org.springframework.boot:spring-boot-starter-webflux-test in test scope.
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webtestclient.autoconfigure.AutoConfigureWebTestClient;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.test.web.reactive.server.WebTestClient;

@SpringBootTest
@AutoConfigureWebTestClient
class ${capitalize(testName(request))}Test {

    @Autowired
    WebTestClient client;

    @Test
    void ${testName(request)}() {
${call.join('\n')}
    }
}
`;
}

const capitalize = (value: string) => value.charAt(0).toUpperCase() + value.slice(1);
